{
 "title": "Nimbus BC local testnet/sim (all nodes)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(process_virtual_memory_bytes,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "resources (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"${instance}\"}[$__rate_interval]) * 100",
     "legendFormat": "CPU usage %"
    },
    {
     "expr": "process_open_fds{instance=\"${instance}\"}",
     "legendFormat": "open file descriptors"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"${instance}\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "sum(nim_gc_mem_bytes{instance=\"${instance}\"})",
     "legendFormat": "Nim GC mem total"
    },
    {
     "expr": "sum(nim_gc_mem_occupied_bytes{instance=\"${instance}\"})",
     "legendFormat": "Nim GC mem used"
    }
   ]
  },
  {
   "title": "version/network (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "version{instance=\"${instance}\"}",
     "legendFormat": "{{version}}"
    },
    {
     "expr": "network_name{instance=\"${instance}\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "open streams (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "libp2p_open_streams{instance=\"${instance}\"}",
     "legendFormat": "{{type}} ({{dir}})"
    }
   ]
  },
  {
   "title": "GC heap objects (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nim_gc_heap_instance_occupied_bytes{instance=\"${instance}\"}",
     "legendFormat": "{{type_name}}"
    }
   ]
  },
  {
   "title": "peers (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "libp2p_peers{instance=\"${instance}\"}",
     "legendFormat": "libp2p peers"
    },
    {
     "expr": "libp2p_pubsub_peers{instance=\"${instance}\"}",
     "legendFormat": "libp2p pubsub peers"
    },
    {
     "expr": "nbc_peers{instance=\"${instance}\"}",
     "legendFormat": "beacon_node peers"
    }
   ]
  },
  {
   "title": "blocks/slot (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(beacon_blocks_received_total{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "received"
    },
    {
     "expr": "rate(beacon_blocks_proposed_total{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "proposed"
    }
   ]
  },
  {
   "title": "peer type (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 15 },
   "targets": [
    {
     "expr": "libp2p_peers_identity{instance=\"${instance}\"}",
     "legendFormat": "{{agent}}"
    }
   ]
  },
  {
   "title": "attestations/slot (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(beacon_attestations_received_total{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "received"
    },
    {
     "expr": "rate(beacon_attestations_sent_total{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "incoming traffic by peer type (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(libp2p_peers_traffic_read_total{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{agent}}"
    }
   ]
  },
  {
   "title": "aggregates/slot (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(beacon_aggregates_received_total{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "outgoing traffic by peer type (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(libp2p_peers_traffic_write_total{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "{{agent}}"
    }
   ]
  },
  {
   "title": "validator rewards / epoch (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(attached_validator_balance_total{instance=\"${instance}\"}[$__rate_interval]) * 384 / 1000000000",
     "legendFormat": "GWei"
    }
   ]
  },
  {
   "title": "validators (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "beacon_active_validators{instance=\"${instance}\"}",
     "legendFormat": "current validators"
    }
   ]
  },
  {
   "title": "SQLite3 (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sqlite3_memory_used_bytes{instance=\"${instance}\"}",
     "legendFormat": "Memory used"
    }
   ]
  },
  {
   "title": "pool.cachedStates (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "beacon_state_data_cache_hits_total{instance=\"${instance}\"} * 100 / (beacon_state_data_cache_hits_total{instance=\"${instance}\"} + beacon_state_data_cache_misses_total{instance=\"${instance}\"})",
     "legendFormat": "cache hit rate"
    }
   ]
  },
  {
   "title": "RSS mem",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"${instance}\"}[$__rate_interval]) * 100"
    }
   ]
  },
  {
   "title": "current slot",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_slot{instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "att'ns sent #all",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 17, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(beacon_attestations_sent_total)"
    }
   ]
  },
  {
   "title": "att'ns recv'd",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_attestations_received_total{instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "current epoch",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_current_epoch{instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "current justified epoch",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 17, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_current_justified_epoch{instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "runtime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "peers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nbc_peers{instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "last finalized epoch",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 17, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "beacon_finalized_epoch{instance=\"${instance}\"}"
    }
   ]
  },
  {
   "title": "Block & attestation delays",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "received attestation delay (s) (${instance})",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 14, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "rate(beacon_attestation_delay_bucket{instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "received aggregate delay (s) (${instance})",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 14, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "rate(beacon_aggregate_delay_bucket{instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "received beacon block delay (s) (${instance})",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 14, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "rate(beacon_block_delay_bucket{instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "storeBlock() duration (s) (${instance})",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 14, "x": 0, "y": 69 },
     "targets": [
      {
       "expr": "rate(beacon_store_block_duration_seconds_bucket{instance=\"${instance}\"}[$__rate_interval])",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  { "title": "Message stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "sync committee msgs/slot (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(beacon_sync_committee_messages_received_total{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "messages"
    },
    {
     "expr": "rate(beacon_sync_committee_contributions_received_total{instance=\"${instance}\"}[$__rate_interval])",
     "legendFormat": "contributions"
    }
   ]
  },
  {
   "title": "dropped msgs/slot (ignored/rejected) (${instance})",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(beacon_blocks_dropped_total{instance=\"${instance}\",reason=\"Ignore\"}[$__rate_interval])",
     "legendFormat": "blocks (I)"
    },
    {
     "expr": "rate(beacon_attestations_dropped_total{instance=\"${instance}\",reason=\"Ignore\"}[$__rate_interval])",
     "legendFormat": "attestations (I)"
    },
    {
     "expr": "rate(beacon_aggregates_dropped_total{instance=\"${instance}\",reason=\"Ignore\"}[$__rate_interval])",
     "legendFormat": "aggregates (I)"
    },
    {
     "expr": "rate(beacon_sync_committee_messages_dropped_total{instance=\"${instance}\",reason=\"Ignore\"}[$__rate_interval])",
     "legendFormat": "sync_msgs (I)"
    },
    {
     "expr": "rate(beacon_sync_committee_contributions_dropped_total{instance=\"${instance}\",reason=\"Ignore\"}[$__rate_interval])",
     "legendFormat": "sync_contribs (I)"
    },
    {
     "expr": "rate(beacon_blocks_dropped_total{instance=\"${instance}\",reason=\"Reject\"}[$__rate_interval])",
     "legendFormat": "blocks (R)"
    },
    {
     "expr": "rate(beacon_attestations_dropped_total{instance=\"${instance}\",reason=\"Reject\"}[$__rate_interval])",
     "legendFormat": "attestations (R)"
    },
    {
     "expr": "rate(beacon_aggregates_dropped_total{instance=\"${instance}\",reason=\"Reject\"}[$__rate_interval])",
     "legendFormat": "aggregates (R)"
    },
    {
     "expr": "rate(beacon_sync_committee_messages_dropped_total{instance=\"${instance}\",reason=\"Reject\"}[$__rate_interval])",
     "legendFormat": "sync_msgs (R)"
    },
    {
     "expr": "rate(beacon_sync_committee_contributions_dropped_total{instance=\"${instance}\",reason=\"Reject\"}[$__rate_interval])",
     "legendFormat": "sync_contribs (R)"
    }
   ]
  }
 ]
}